### ISSUE TITLE
Unable to list installations

### ISSUE THREAD

**Issue by filipvh** [yanyongyu/githubkit#104]
It seems the documentation of GitHub says you need a JWT to be able to list app installations.
See https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#list-installations-for-the-authenticated-app

`You must use a [JWT](https://docs.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.`

But it seems this library has flaged this endpoint not to be called with JWT but with basic auth
[ /auth/_url.py](https://github.com/yanyongyu/githubkit/blob/44394d035f891a3668cb6fdc3026317ab3752c91/githubkit/auth/_url.py#L11)

**Comment by yanyongyu** [comment]
From [the link you provide](https://github.com/yanyongyu/githubkit/blob/44394d035f891a3668cb6fdc3026317ab3752c91/githubkit/auth/_url.py#L11), githubkit checks the api url. If the url matches one of `APP_ROUTES`, githubkit will [use jwt](https://github.com/yanyongyu/githubkit/blob/44394d035f891a3668cb6fdc3026317ab3752c91/githubkit/auth/app.py#L178) to auth as the app it self.

Did you encounter any errors? if so, please provide some error logs and repreduce steps.

**Comment by yanyongyu** [comment]
If you encountered any errors, you can open a new issue with error logs.
