### ISSUE TITLE
Some typing classes are not public

### ISSUE THREAD

**Issue by FeodorFitsner** [yanyongyu/githubkit#106]
Thanks for the great library - it's async and typed!

While using some of the API methods, for example `github.rest.pulls.async_create_review()` I noticed it's signature requires `ReposOwnerRepoPullsPullNumberReviewsPostBody` which I was unable to import:

<img width="738" alt="image" src="https://github.com/yanyongyu/githubkit/assets/5041459/393afc5a-8c06-4774-87be-571e499000ba">

I imported and used `ReposOwnerRepoPullsPullNumberReviewsPostBody` instead and review was successfully added.

Am I using it wrongfully or there is a bug?

**Comment by yanyongyu** [comment]
The type `ReposOwnerRepoPullsPullNumberReviewsPostBodyType` is actually a `TypedDict`, you could simply pass python dict as the argument. The IDE could detect the TypedDict and prompt you the field name, check the field value type.

**Comment by FeodorFitsner** [comment]
Yep, that worked. Thanks!

...though using strings instead of parameters is not so elegant :)

Would it make sense to export those classes from a module?

**Comment by yanyongyu** [comment]
> though using strings instead of parameters is not so elegant

I'm not sure how you are using the strings? you can just pass dicts or lists likes `data={"body": "xxx", "comments": []}`

> Would it make sense to export those classes from a module?

The types can be actually imported from the types module i mentioned above:

```python
from githubkit.versions.latest.types import ReposOwnerRepoPullsPullNumberReviewsPostBodyType
```

**Comment by yanyongyu** [comment]
If there is any other questions, feel free to open an issue. i will close this.
