### ISSUE TITLE
Github Enterprise API causes type import errors

### ISSUE THREAD

**Issue by FaeyUmbrea** [yanyongyu/githubkit#107]
Using the ghec version of the api causes "cannot import name" issues across the entirety of the model data.

**Comment by FaeyUmbrea** [comment]
I've investigated it a bit more and it appears as though the issue is due to the runtime failing to resolve the symbols from the ghec variant, although I can not figure out any reason why it should fail, considering the code is pretty much identical.

The failure also is reproducable simply by importing any of the models from the ghec variant.

**Comment by yanyongyu** [comment]
Could you please provide your repreduce code and the error message?

**Comment by FaeyUmbrea** [comment]
Unfortunately, the code itself is under NDA, but I can provide a snippet that is capable of reproducting the bug.

As little as

`from githubkit.versions.ghec_v2022_11_28.models import Runner`

will cause

`cannot import name 'runner' from 'githubkit.version.ghec_v2022_11_28.models' ([path to __init__.py])`

**Comment by yanyongyu** [comment]
I can reproduce this error. It's due to a stupid error that i forget adding the module to lazy loading list :joy:
