### ISSUE TITLE
Some timeline events are missing

### ISSUE THREAD

**Issue by pvcnt** [yanyongyu/githubkit#110]
Some timeline events are missing. For example, I was looking for [`head_ref_force_pushed`](https://docs.github.com/en/rest/using-the-rest-api/issue-event-types?apiVersion=2022-11-28#head_ref_force_pushed) and I do not see it in https://github.com/yanyongyu/githubkit/blob/master/githubkit/versions/v2022_11_28/rest/issues.py#L2871-L2895

It looks like other events may be missing as well.

**Comment by yanyongyu** [comment]
This event is a `StateChangeIssueEvent`. githubkit generates the models from the github's openapi schema. It's impossible to miss an event type unless github miss the event. In fact, many timeline events on GitHub use this type and has no extra detailed info.

**Comment by pvcnt** [comment]
Ah... I was expecting something more typed, like there is in the GraphQL API. Thank you for clarifying this!
