### ISSUE TITLE
Feature: GraphQL Pagination

### ISSUE THREAD

**Issue by tisonkun** [yanyongyu/githubkit#112]
Something like https://github.com/octokit/plugin-paginate-graphql.js

**Comment by yanyongyu** [comment]
I'm not familiar with GraphQL pagination queries, but I can give it a try 😄

**Comment by tisonkun** [comment]
@yanyongyu The main design of the SDK above is a convention:

```
        pageInfo {
          hasNextPage
          endCursor
        }
```

that the GraphQL query must have the `pageInfo` section. And it will extract the related fields to fulfill `after: $cursor`.

It should be possible for users to handle this iteration logic manually but an out-of-the-box API can help.

**Comment by tisonkun** [comment]
And here is the related GitHub docs: https://docs.github.com/en/graphql/guides/using-pagination-in-the-graphql-api

**Comment by yanyongyu** [comment]
After a deep understanding of octokit plugin paginate graphql, I'll record some key points and notes here:

- graphql pagination relies on the `pageInfo` object, and should be defined by user in the query.
- graphql pagination should define an input cursor variable and octokit supports create cursor var name dynamically.
- octokit does not support nested pagination and it seems hard to achieve.
- octokit finds the `pageInfo` key of dicts recursively to detect pagination. [[Ref]](https://github.com/octokit/plugin-paginate-graphql.js/blob/bf40664a9b7881b57d4a73434387bd69fa56ed5c/src/object-helpers.ts#L6-L15)
- octokit finds the path of the `pageInfo` object and merges the `nodes` and `edges` [[Ref]](https://github.com/octokit/plugin-paginate-graphql.js/blob/bf40664a9b7881b57d4a73434387bd69fa56ed5c/src/merge-responses.ts#L3-L35)
- the main logic of iteration is [here](https://github.com/octokit/plugin-paginate-graphql.js/blob/bf40664a9b7881b57d4a73434387bd69fa56ed5c/src/iterator.ts#L6-L42).
- octokit supports both forward and backward page iteration by detecting the `hasNextPage`/`endCursor` and `hasPreviousPage`/`startCursor` key of the page info.
