### ISSUE TITLE
ImportError: cannot import name 'User' from 'githubkit.versions.latest.models'

### ISSUE THREAD

**Issue by BhuwanPandey** [yanyongyu/githubkit#119]
Is there anything that am I missing?
What the reason  that  getting this error eventhough I have setup up githubkit in virtualenv well.
with poetry add githubkit[auth-app]

file.py

```python
from githubkit import GitHub
from githubkit.versions.latest.models import User
```

Error reproduce when run
python file.py 
on Window 11
Python version 3.11
Poetry version 1.3.2

**Comment by yanyongyu** [comment]
It seems the code example in the readme is outdated. GitHub has changed the model name of `User` into `PrivateUser | PublicUser`. I will update the examples in the readme.

**Comment by yanyongyu** [comment]
You can simply remove the type hint and you can see the inferred type of the return value from IDE.

**Comment by BhuwanPandey** [comment]
I have a question that
Is this package allow to return authorize url like
https://github.com/login/oauth/authorize?response_type=code&client_id=codeID&redirect_uri=REDIRECT_URL&scope=user+user%3Aemail

I am new to this package, when i visit readme section, may be i missed, I didnot get it.

**Comment by yanyongyu** [comment]
>  I have a question that
> Is this package allow to return authorize url like
> https://github.com/login/oauth/authorize?response_type=code&client_id=codeID&redirect_uri=REDIRECT_URL&scope=user+user%3Aemai

In the oauth flow, you should redirect user to the authorize page first. After user authorized your app, github will redirect user to your callback url. You can get the `code` from the callback url and give the code to githubkit to exchange access token.

In the flow above, you should handle the web related things by yourself, including redirect user to authorize and handle the callback from github. githubkit will use the code to exchange `access_token` and you can use the token to act as user.
