### ISSUE TITLE
GraphQL usage with `githubkit`

### ISSUE THREAD

**Issue by marckhair** [yanyongyu/githubkit#132]
Hey,

I am writing my first GraphQL queries with `githubkit`. Do you see anything wrong with my usage? I can't seem to get my queries to work. The queries are successful in my GraphQL explorer.

```python
async with GitHub(
    github_token, base_url="https://<myenterprisegithuburl>.com/api/graphql"
) as github_client:

    resp = await github_client.async_graphql(
        query="""
            query myQuery($owner: String!, $name: String!) {
                repository(owner: $owner, name: $name){
                    id
                }
            }
        """,
        variables={
            "owner": owner,
            "name": repo
        }
    )
```

**Comment by yanyongyu** [comment]
Did you encounter an error? Could you please provide the error log?

**Comment by marckhair** [comment]
@yanyongyu the problem was that `githubkit` appended `/graphql` to my base url. I was not expecting that.

**Comment by marckhair** [comment]
@yanyongyu  Since I was specifying `"https://<myenterprisegithuburl>.com/api/graphql"` as my base URL, the GraphQL requests were getting POSTed to `"https://<myenterprisegithuburl>.com/api/graphql/graphql"`

**Comment by yanyongyu** [comment]
The base url is actually the server base url both for rest and graphql api. So you dont need to append the graphql endpoint to it.

Feel free to ask questions if you encounter any problem. Enjoy githubkit.
