### ISSUE TITLE
Differences between regular GH and GHES API graphql endpoints

### ISSUE THREAD

**Issue by fau-st** [yanyongyu/githubkit#133]
Hello,

I'm successfully using this library to interact with a GitHub Enterprise Server through the REST API.
As you may know, for GHES, the REST API endpoint is located at `https://[hostname]/api/v3/` instead of `https://api.github.com/`.
So far so good as I can use the `base_url` parameter when building a `GitHub` object.

However, the troubles appear when I try to make a request using the graphql endpoint.
Indeed, GHES uses this endpoint for graphql : `https://[hostname]/api/graphql/` (the `v3/` suffix is no longer present) and I can no longer use `base_url` because it's different whether I use the REST or graphql API.

Sample code :
```python
from githubkit import (
    AppAuthStrategy,
    GitHub,
)

INSTALLATION_ID: int = ...
auth_strategy: AppAuthStrategy = ...

gh = GitHub(
    auth_strategy.as_installation(INSTALLATION_ID),
    base_url='https://ghes-hostname/api/v3',
)

gh.graphql('query { viewer { login } }')
# >>> githubkit.exception.RequestFailed: Response(404 Not Found, data_model=typing.Any)
```
Here, `githubkit` successfully retrieves a token through the REST API to use for the graphql query but then this query is made against `https://ghes-hostname/api/v3/graphql` and a 404 response is returned.

I'd like to know your opinion on this as supporting GHES might not be your priority. Let me know if you need more information.

**Comment by yanyongyu** [comment]
According to octokit, a workaround for GHES is needed. https://github.com/octokit/graphql.js/blob/dae781b027c19bcd458577cd9ac6ca888b2fdfeb/src/graphql.ts#L67-L72

**Comment by yanyongyu** [comment]
Maybe a direct patch to endpoint url in graphql request function looks clearer. i will create a pr when i am free.

**Comment by yanyongyu** [comment]
Hi @fau-st , i have just create a PR to fix this, but i do not have a GHES account to test this. Could you please test or review the code to verify the graphql endpoint? you can install the githubkit from the [fix/ghes-graphql](https://github.com/yanyongyu/githubkit/tree/fix/ghes-graphql) branch.

**Comment by yanyongyu** [comment]
I just added some tests and docs about the `base_url` option in readme.
