### ISSUE TITLE
[Question] How do I access the latest tags and get the commit of that tag and git attirbutes 

### ISSUE THREAD

**Issue by Redhawk18** [yanyongyu/githubkit#136]
Hey! I'm writing an update script for nixpkgs where I need the newest tag of this repo, and to get the commit hash. Then I also need to get the commit hash of the `ocgcore` git attribute. I couldn't figure out how to do it with the readme doc and my lsp guiding me so I wanted to ask.

https://github.com/edo9300/edopro

**Comment by Redhawk18** [comment]
@yanyongyu Thank you, that helped a lot but back to my original question I linked a repo, how do I get the commit of a git attribute?  `ocgcore` is my example here.

**Comment by yanyongyu** [comment]
> get the commit of a git attribute

I do not quite understand this, what does the `ocgcore` mean? By using the GitHub rest API, you can get the commit info by commit SHA, branch name, tag name.

githubkit is a GitHub API SDK, you may find the API you need in the github [rest api docs](https://docs.github.com/en/rest?apiVersion=2022-11-28) or [graphql docs](https://docs.github.com/en/graphql). If you cannot find a satisfied API for your needs, githubkit also can not give the result for you.

**Comment by Redhawk18** [comment]
> > get the commit of a git attribute
> 
> I do not quite understand this, what does the `ocgcore` mean? By using the GitHub rest API, you can get the commit info by commit SHA, branch name, tag name.
> 
> githubkit is a GitHub API SDK, you may find the API you need in the github [rest api docs](https://docs.github.com/en/rest?apiVersion=2022-11-28) or [graphql docs](https://docs.github.com/en/graphql). If you cannot find a satisfied API for your needs, githubkit also can not give the result for you.

It's in the repo I linked, like I said `ocgcore` is a git attribute of another repo. I want to get the commit of that git attribute. How does this library work with git attributes?

**Comment by Redhawk18** [comment]
My mistake they are called git modules, not git attributes.

**Comment by yanyongyu** [comment]
I see... You want to get the submodule commit sha. You can use the [Get Repo Content API](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#get-repository-content). It's very simple:

```python
g = GitHub("token here")
resp = g.rest.repos.get_content("edo9300", "edopro", "ocgcore")
info: ContentSubmodule = resp.parsed_data
sha = info.sha
```

> how do I download or read the contents of files in repos

Using the same api above, you will get a `content` field (file content in base64 format) and a field called `download_url` in the response data. Or, you can add a header to get the raw content of the file (100MB limited).

```python
g = GitHub("token here")
resp = g.rest.repos.get_content(
    "edo9300",
    "edopro",
    "README.md",
    headers={"Accept": "application/vnd.github.raw+json"},
)
print(resp.text)
```
