### ISSUE TITLE
Mock REST-API call

### ISSUE THREAD

**Issue by mattibo** [yanyongyu/githubkit#138]
Hi,

thank you for the wonderful library. I use it quite a lot. Right now I would like to write a unit test for my own logic. Inside my logic I call the GitHub REST-API with githubkit. I did not manage to mock a call like

```python
github.rest.repos.get(owner="owner", repo="repo")
```

I tried it like this: https://stackoverflow.com/questions/39457108/how-to-mock-nested-multiple-layers-of-return-objects-in-python

Do you have a tip how to mock githubkit?

**Comment by yanyongyu** [comment]
It seems you need to mock the githubkit's request and return the fake response data to your code. I think you can monkey patch the `request` function of the `github` instance.

**Comment by yanyongyu** [comment]
I have just made a example mock function by pytest. I will add it to the readme docs.
