### ISSUE TITLE
Bug: Webhooks `InstallationCreated` field `requester` schema error

### ISSUE THREAD

**Issue by birkjernstrom** [yanyongyu/githubkit#14]
Hi,

First of all: Thanks for an amazing effort and contribution creating this library! I had the same idea a few weeks ago before I fortunately stumbled over this one <3

## Issue

- Receiving a Webhook of type `installation.created`
- `requester` is null (None) in the webhook received
- Pydantic throws a validation error that `requester` cannot be None

## Proposal
Change template to expand `Unset` to `Unset, None` within the Union type definitions and set None as the default? Or change the validator to check for `is None` as well `UNSET`?

**Comment by birkjernstrom** [comment]
Happy to make a PR for this. Just not 100% sure I'm following the intent with `Unset` and whether I'm thinking about it correctly or if there is a better approach

**Comment by yanyongyu** [comment]
Hi, thank you for finding a error in webhooks schema. `githubkit` generates the webhooks model from https://github.com/octokit/webhooks. I find the error schema field [here](https://github.com/octokit/webhooks/blob/faf3445d0a73430bb1c85889e6739d019de84f0b/payload-schemas/api.github.com/installation/created.schema.json#L34). octokit seems to assume this field to be `User, not null`. If you actually received a `null` value, i can make a `schema patch` in the `pyproject.toml` file.

**Comment by yanyongyu** [comment]
I find the example model in [github docs](https://docs.github.com/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#installation). This field is `object or null`.

**Comment by yanyongyu** [comment]
A new release is published which has fixed this error. By the way, `UNSET` means field missing in data, `None` means that the field exists in the data with a value `null`.

**Comment by birkjernstrom** [comment]
Thank you so much @yanyongyu ! Sorry for the late response, it got completely lost amongst notifications.
