### ISSUE TITLE
Schema error when creating check run

### ISSUE THREAD

**Issue by fau-st** [yanyongyu/githubkit#148]
Hello,

With version `0.11.12` it seems that creating a check run is no longer possible:
```python
gh.rest.checks.create(
    owner='owner',
    repo='repo',
    name='name',
    head_sha='0000000000000000000000000000000000000000',
    status='in_progress',
)
```
:arrow_down: 
```
pydantic.errors.PydanticUserError: Model 'ReposOwnerRepoCheckRunsPostBodyOneof1' needs field 'status' to be of type `Literal`
```

It looks like it's related to the changes made to [githubkit/versions/v2022_11_28/rest/checks.py](https://github.com/yanyongyu/githubkit/commit/3865ae3bb623e1c95f20e00689f5baed39b6303c#diff-18623225250380172d2b302ee8f336c50437d25fdcdcec08833ae827ce09fea3) but I'm not sure why it was modified.

**Comment by yanyongyu** [comment]
This error is also caused by upstream schema changes. GitHub added a discriminator to this api's body description. The discriminator points to the `status` field, but one of the schema's `status` field is not required. This causes pydantic raises an error. A schema patch is needed to fix this.

**Comment by yanyongyu** [comment]
It seems this upstream schema change also caused another error. The `status` field's allowed value list is also overrided by the `oneOf`.
