### ISSUE TITLE
[question] How do I access the date of a commit?

### ISSUE THREAD

**Issue by Redhawk18** [yanyongyu/githubkit#155]
I can see with `commit.json()` theres is a date field but this is also deprecated so I wanted to know the proper way to access this field.

**Comment by Redhawk18** [comment]
I tried looking into both `author` and `committer`, but neither object have the date.
```
{... 'author': {'name': 'Edoardo Lolletti', 'email': 'edoardo762@gmail.com', 'date': '2023-02-18T13:37:33Z'}, 'committer': {'name': 'Edoardo Lolletti', 'email': 'edoardo762@gmail.com', 'date': '2023-02-18T13:37:33Z'}, ...}
```

**Comment by yanyongyu** [comment]
> I tried looking into both `author` and `committer`, but neither object have the date.

You mean the `date` field is not exist in the `committer` object? I'm not sure how to get the date using GitHub API correctly, but you can get the date using git or extract from commit patch file.

**Comment by yanyongyu** [comment]
After searching for the github docs, you can get the commit date using the graphql api. You can query for the commit object which contains the `committedDate` field.

**Comment by Redhawk18** [comment]
> > I tried looking into both `author` and `committer`, but neither object have the date.
> 
> You mean the `date` field is not exist in the `committer` object? I'm not sure how to get the date using GitHub API correctly, but you can get the date using git or extract from commit patch file.

But the date is in the json blob I sent but not in the objects? How can that be?

**Comment by yanyongyu** [comment]
I don't quite understand what you mean. But, you can get the commit object by using github rest api like this:

```python
from githubkit import GitHub

g = GitHub()

resp = g.rest.git.get_commit("owner", "repo", "commit_sha")
commit = resp.parsed_data
date = commit.committer.date
```

**Comment by Redhawk18** [comment]
hm I'm not sure

```py
<class 'githubkit.versions.v2022_11_28.models.group_0001.SimpleUser'>
Traceback (most recent call last):
  File "/home/redhawk/code/nixpkgs/pkgs/by-name/ed/edopro/update.py", line 33, in <module>
    print(irrlicht.committer.date)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/kbxv83nrbh47f8jnhfl1p222phl44152-python3.11-pydantic-2.6.3/lib/python3.11/site-packages/pydantic/main.py", line 767, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'SimpleUser' object has no attribute 'date'
```
```py
with GitHub(UnauthAuthStrategy()) as github:
    edopro: Tag = github.rest.repos.list_tags("edo9300", "edopro").parsed_data[0]

    ocgcore: ContentSubmodule = github.rest.repos.get_content(
        "edo9300", "edopro", "ocgcore"
    ).parsed_data

    # This dep is not versioned in anyway and is why we check below to see if this is a new version.
    irrlicht: Commit = github.rest.repos.list_commits(
        "edo9300", "irrlicht1-8-4"
    ).parsed_data[0]

    irrlicht: Commit = github.rest.repos.get_commit(
        "edo9300", "irrlicht1-8-4", "7edde28d4f8c0c3589934c398a3a441286bb7c22"
    ).parsed_data


print(type(irrlicht.committer))
print(irrlicht.committer.date)
```

**Comment by yanyongyu** [comment]
If you use the `repos.get_commit` api, you should use `irrlicht.commit.committer and irrlicht.commit.committer.date`.

In the example above, i'm using the `git.get_commit` api which queries the git database directly.
