### ISSUE TITLE
How to conveniently convert paginate result to pandas DataFrame?

### ISSUE THREAD

**Issue by tisonkun** [yanyongyu/githubkit#19]
Said I fetch the pulls as:

```py
    c = obtain_client()
    prs = c.paginate(
        c.rest.pulls.list,
        owner="apache",
        repo="pulsar",
        state="open")
```

Now `prs` is a generator of `PullRequestSimple` list. How can I convert it to a pandas DataFrame as:

```
   url id node_id ... draft
0 ... nnn mmm ... False
...
```

**Comment by tisonkun** [comment]
I just found a way now:

```py
    c = obtain_client()
    prs = c.paginate(
        c.rest.pulls.list,
        owner="apache",
        repo="pulsar",
        state="open")
    df = pd.DataFrame([vars(pr) for pr in prs])
```

But I still wonder if we can provide some utilities to interoperate with pandas smoothly.

**Comment by yanyongyu** [comment]
`githubkit` uses [pydantic](https://docs.pydantic.dev/) model to serialize data. You can search for the way to convert pydantic models into pandas DataFrame. In the code above, you may change the `vars(pr)` into `pr.dict()`. More infomation about the usage, you can check the [pydantic docs](https://docs.pydantic.dev/)

**Comment by tisonkun** [comment]
@yanyongyu Thank you!
