### ISSUE TITLE
Feature: Support custom headers

### ISSUE THREAD

**Issue by zegl** [yanyongyu/githubkit#29]
Hey!

Many GitHub endpoints for _events_, including `list_public_events`, `list_events_for_timeline`, `list_events`, `list_events_for_authenticated_user` supports `ETag` and `If-None-Match` headers (see [docs](https://docs.github.com/en/rest/activity/events?apiVersion=2022-11-28#about-github-events)).

I think that it would be convenient if githubkit would support setting the `If-None-Match` header, and correct parsing of `304 Not Modified` responses, as this is currently not possible with the generated methods.

**Comment by yanyongyu** [comment]
I see.. I may try to add a `headers` keyword argument to client methods if there is no field named `headers`.

For the `304 Not Modified`, currently is treated as successful response, and the return code is in the reponse object `response.status_code`. we could restrict the response status code checking to raise an exception. But, should we raise an exception for `304`?

**Comment by yanyongyu** [comment]
headers now can be customed in client request as a keyword only param. :)

**Comment by zegl** [comment]
Amazing! This looks great! ⭐️
