### ISSUE TITLE
Bug: `TeamOrganization` company and email may be null

### ISSUE THREAD

**Issue by bgreman-driscolls** [yanyongyu/githubkit#31]
Any time I try to access the `parsed_data` field on various responses, I receive a pydantic validation error, I believe because the org data is missing a value for `company` and `email`.  These values are null in the REST API response for `orgs/<org_name>`.

For example:
```python
test_team_resp = ghkapi.rest.teams.get_by_name(org=ORG_NAME, team_slug="DevSecOps")
test_team = resp.parsed_data
```
Gives:

```python
pydantic.error_wrappers.ValidationError: 2 validation errors for ParsingModel[TeamFull]
__root__ -> organization -> company
  none is not an allowed value (type=type_error.none.not_allowed)
__root__ -> organization -> email
  none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by yanyongyu** [comment]
This may be an error in github's schema. I will make a schema patch after report the issue to https://github.com/github/rest-api-description.

**Comment by bgreman-driscolls** [comment]
https://github.com/github/rest-api-description/issues/2507
