### ISSUE TITLE
False positive type intelligence

### ISSUE THREAD

**Issue by tisonkun** [yanyongyu/githubkit#39]
<img width="1167" alt="image" src="https://github.com/yanyongyu/githubkit/assets/18818196/2e9f1749-2de9-40c8-8979-20250e9fa2d6">

This code can properly work but PyCharm hint a type mismatch.

**Comment by yanyongyu** [comment]
duplicate of #27 

The type hint works fine in vscode pylance/pyright and not work on pycharm due to the bugs of pycharm type checking.

**Comment by tisonkun** [comment]
Thanks for your information! Closing...
