### ISSUE TITLE
Release upgrade to pydantic

### ISSUE THREAD

**Issue by criemen** [yanyongyu/githubkit#46]
Hey, we're using githubkit together with apache-airflow. The current apache-airflow version requires pydantic v2, but this package pulls in v1, resulting in a conflict.
Would it be possible to cut a new release that includes https://github.com/yanyongyu/githubkit/pull/45?
Thanks a lot in advance!

**Comment by yanyongyu** [comment]
Since #45 includes huge breaking changes and is not fully validated, i would like to create an alpha release before it can easily migrate to pydantic v2.

**Comment by yanyongyu** [comment]
Pydantic v2 support is now included in [v0.11.0a0](https://github.com/yanyongyu/githubkit/releases/tag/v0.11.0a0) pre-release.
