### ISSUE TITLE
Bug: `pull request simple` field `head.repo` schema incorrect

### ISSUE THREAD

**Issue by tisonkun** [yanyongyu/githubkit#6]
```python
g = ... # obtain the client
prs = g.paginate(g.rest.pulls.list, owner='apache', repo='pulsar', state='open')
pr = next(prs)
```

gives:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.10/site-packages/githubkit/paginator.py", line 76, in __next__
    contents = self._get_next_page()
  File "/opt/homebrew/lib/python3.10/site-packages/githubkit/paginator.py", line 112, in _get_next_page
    cast(Response[List[RT]], response).parsed_data
  File "/opt/homebrew/lib/python3.10/site-packages/githubkit/response.py", line 50, in parsed_data
    return parse_raw_as(self._data_model, self._response.content)
  File "pydantic/tools.py", line 82, in pydantic.tools.parse_raw_as
  File "pydantic/tools.py", line 38, in pydantic.tools.parse_obj_as
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 7 validation errors for ParsingModel[List[githubkit.rest.models.PullRequestSimple]]
__root__ -> 27 -> head -> repo
  none is not an allowed value (type=type_error.none.not_allowed)
__root__ -> 36 -> head -> repo
  none is not an allowed value (type=type_error.none.not_allowed)
__root__ -> 39 -> head -> repo
  none is not an allowed value (type=type_error.none.not_allowed)
__root__ -> 44 -> head -> repo
  none is not an allowed value (type=type_error.none.not_allowed)
__root__ -> 67 -> head -> repo
  none is not an allowed value (type=type_error.none.not_allowed)
__root__ -> 85 -> head -> repo
  none is not an allowed value (type=type_error.none.not_allowed)
__root__ -> 94 -> head -> repo
  none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by tisonkun** [comment]
It looks like the `head` response can be none but the type annotation indicate it must not be none.

**Comment by tisonkun** [comment]
Workaround now by passing `map_func=lambda x: x.json()`

**Comment by yanyongyu** [comment]
it seems like there is an error in gh rest api definition or codegen. I will take a look at your example.

**Comment by yanyongyu** [comment]
by the way, which client auth strategy you are using? i think the missing of repo field may be caused by the permission of github app. github app can not get any repo info if the app is not installed on it and the repo field may be none

**Comment by tisonkun** [comment]
cc @yanyongyu I'd like to know whether you can reproduce the case now.

**Comment by yanyongyu** [comment]
yes, i can reproduce the error.

**Comment by yanyongyu** [comment]
In the gh schema, the repo field of pull request head object is `"$ref": "#/components/schemas/repository"` and cannot be nullable. we may need to patch the schema and repo the issue to [github/rest-api-description](https://github.com/github/rest-api-description)

**Comment by yanyongyu** [comment]
i have created an issue https://github.com/github/rest-api-description/issues/1811 related to this and make a patch to githubkit until the schema is corrected.

**Comment by tisonkun** [comment]
Cool! Yes, I think we should patch downstream here...the challenge may be preventing codegen from accidental regression (that is, you may some fix, but the codegen revert it, lol). Or if you can oversee all the commits, a manual fix can work for now.

**Comment by tisonkun** [comment]
Shall we have a v0.9.1 release for this fix?

**Comment by yanyongyu** [comment]
yeah, i'm bumping the version to make a new release.

**Comment by yanyongyu** [comment]
the new version of githubkit will be available after the ci complete 🍻
