### ISSUE TITLE
Use HTTP caching

### ISSUE THREAD

**Issue by karpetrosyan** [yanyongyu/githubkit#61]
Hi! First, thanks for this amazing package.

I'm wondering if you can use [Hishel](https://hishel.com) to reduce network traffic and possibly save some rate limits.
Users will be able to save time on responses that support caching (almost every github response).

You could enable in-memory caching at the library level and provide an API to the hishel so users can configure caching and possibly store responses in persistent storage so they can reuse cached responses across multiple executions.

There is also a [useful example in the documentation](https://hishel.com/examples/github/) that shows how effective caching can be when working with the github APIs.

If you decide to add this feature, I will gladly submit a pull request!

**Comment by yanyongyu** [comment]
The token cache is used in the auth strategy, and the strategy can read configs from the github instance. so, github could be the only entry point and auth strategy could also get the storage provider from it.
