### ISSUE TITLE
Release Pre-Release to install pydantic 2>

### ISSUE THREAD

**Issue by vQid** [yanyongyu/githubkit#63]
Current release does not support pydantic v2 and above, I already updated my projects to version 2 and above and have to install the pre release of githubkit explicitly.

**Comment by yanyongyu** [comment]
Hey, the pydantic v2 pre-release has already been released here: https://github.com/yanyongyu/githubkit/releases/tag/v0.11.0a0

you can install it using `pip install --pre` or `poetry add --allow-prerelease` etc.
