### ISSUE TITLE
The library consumes too much RAM. It also consumes a lot of CPU at startup.

### ISSUE THREAD

**Issue by Arkptz** [yanyongyu/githubkit#76]
![image](https://github.com/yanyongyu/githubkit/assets/58850875/ab477977-af30-48f1-aaea-eb0900cc35b9)

**Comment by Arkptz** [comment]
![image](https://github.com/yanyongyu/githubkit/assets/58850875/346f04e6-be0b-49fe-ab96-3ad1550bbf44)
it's startup

**Comment by yanyongyu** [comment]
Due to the huge number of pydantic model used to validate data, githubkit needs a lot of memory currently. But, i'm working on lazy loading the models when using to reduce the cost when importing.

related to #54
