### ISSUE TITLE
Feature: Support GitHub REST API versioning

### ISSUE THREAD

**Issue by tisonkun** [yanyongyu/githubkit#9]
See also https://docs.github.com/en/rest/overview/api-versions

@yanyongyu it can be a thing that GitHub versions its API endpoints :)

**Comment by yanyongyu** [comment]
The versioning of rest-api can be hard to support until the [github/rest-api-description](https://github.com/github/rest-api-description) support it. Changing the rest api version will cause model definitions and client methods to change.

**Comment by yanyongyu** [comment]
https://github.com/github/rest-api-description/ has added [versioned schema](https://raw.githubusercontent.com/github/rest-api-description/main/descriptions-next/api.github.com/api.github.com.2022-11-28.yaml).

**Comment by yanyongyu** [comment]
githubkit currently does not specify a rest api version and github will use the default version. But githubkit now generates the model using the latest model instead of `2022-11-28`. We may change this behavior first.

**Comment by yanyongyu** [comment]
Due to #11, the core logic of codegen may change. For now, i would like to add the version tag to codegen and output the version header in client request.
